# Generated by Django 3.1.12 on 2025-03-24 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='职位编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位名称')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='公司名称')),
                ('salary', models.CharField(blank=True, max_length=50, null=True, verbose_name='薪资待遇')),
                ('place', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作地点')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历要求')),
                ('experience', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作经验')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='职位标签')),
                ('company_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司类型')),
                ('company_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='公司规模')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
                'db_table': 'job_data',
            },
        ),
        migrations.CreateModel(
            name='SpiderInfo',
            fields=[
                ('spider_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='爬虫编号')),
                ('count', models.IntegerField(default=0, verbose_name='爬取次数')),
                ('page', models.IntegerField(default=0, verbose_name='爬取页数')),
            ],
            options={
                'verbose_name': '爬虫信息',
                'verbose_name_plural': '爬虫信息',
                'db_table': 'spider_info',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户账号')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('pass_word', models.CharField(max_length=20, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'user_list',
            },
        ),
        migrations.CreateModel(
            name='UserExpect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_word', models.CharField(max_length=20, verbose_name='期望职位')),
                ('place', models.CharField(max_length=20, verbose_name='期望城市')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.userlist', verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '用户期望',
                'verbose_name_plural': '用户期望',
                'db_table': 'user_expect',
            },
        ),
        migrations.CreateModel(
            name='SendList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=100, verbose_name='职位编号')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投递时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.userlist', verbose_name='用户账号')),
            ],
            options={
                'verbose_name': '投递记录',
                'verbose_name_plural': '投递记录',
                'db_table': 'send_list',
                'unique_together': {('user', 'job_id')},
            },
        ),
    ]
