# Generated by Django 3.1.12 on 2025-03-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendlist',
            options={'ordering': ['-created_at'], 'verbose_name': '投递记录', 'verbose_name_plural': '投递记录'},
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投递时间'),
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='job_id',
            field=models.CharField(max_length=255, verbose_name='职位ID'),
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.userlist', verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='sendlist',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='sendlist',
            table='job_sendlist',
        ),
    ]
