# Generated by Django 3.1.12 on 2025-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20250326_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendlist',
            options={'verbose_name': '投递记录', 'verbose_name_plural': '投递记录'},
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='sendlist',
            name='job_name',
        ),
        migrations.AlterField(
            model_name='sendlist',
            name='job_id',
            field=models.CharField(max_length=50, verbose_name='职位ID'),
        ),
    ]
