# Generated by Django 3.1.12 on 2025-04-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20250406_1254'),
    ]

    operations = [
    ]
