# Generated by Django 3.1.12 on 2025-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20250406_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendlist',
            name='created_at',
            field=models.DateTimeField(verbose_name='投递时间'),
        ),
    ]
